### ISSUE TITLE
Allow using without `xsel` if not utilizing clipboard functionality

### ISSUE THREAD

**Issue by thenbe** [ff6347/to-markdown-cli#250]
```log
/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/lib/linux.js:14
                error = new Error('Couldn\'t find the `xsel` binary and fallback didn\'t work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel');
                       ^

Error: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel
    at makeError (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/lib/linux.js:14:11)
    at xselWithFallbackSync (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/lib/linux.js:43:10)
    at Object.pasteSync (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/lib/linux.js:56:24)
    at exports.readSync (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/index.js:42:38)
    at parseFlags (file:///home/nbe/.local/share/pnpm/global/5/.pnpm/to-markdown-cli@1.0.0/node_modules/to-markdown-cli/dist/lib/parse-flags.js:11:39)
    at file:///home/nbe/.local/share/pnpm/global/5/.pnpm/to-markdown-cli@1.0.0/node_modules/to-markdown-cli/dist/html2md.js:63:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  fallbackError: Error: spawnSync /home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/fallbacks/linux/xsel ENOENT
      at Object.spawnSync (node:internal/child_process:1110:20)
      at Object.spawnSync (node:child_process:871:24)
      at module.exports.sync (/home/nbe/.local/share/pnpm/global/5/.pnpm/execa@1.0.0/node_modules/execa/index.js:334:30)
      at xselWithFallbackSync (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/lib/linux.js:41:17)
      at Object.pasteSync (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/lib/linux.js:56:24)
      at exports.readSync (/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/index.js:42:38)
      at parseFlags (file:///home/nbe/.local/share/pnpm/global/5/.pnpm/to-markdown-cli@1.0.0/node_modules/to-markdown-cli/dist/lib/parse-flags.js:11:39)
      at file:///home/nbe/.local/share/pnpm/global/5/.pnpm/to-markdown-cli@1.0.0/node_modules/to-markdown-cli/dist/html2md.js:63:5
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawnSync /home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/fallbacks/linux/xsel',
    path: '/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/fallbacks/linux/xsel',
    spawnargs: [ '--clipboard', '--output' ],
    stdout: null,
    stderr: null,
    failed: true,
    signal: null,
    cmd: '/home/nbe/.local/share/pnpm/global/5/.pnpm/clipboardy@2.1.0/node_modules/clipboardy/fallbacks/linux/xsel --clipboard --output',
    timedOut: false
  }
}

Node.js v18.15.0

```

It would require catching that error from `clipboardy`.

**Comment by ff6347** [comment]
Hi @thenbe yes good idea. What do you think about just logging the error 
```
'Couldn\'t find the `xsel` binary and fallback didn\'t work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel'
```          
and exit with error code 1 if the user tries to use the clipboard without xsel installed?

**Comment by thenbe** [comment]
@ff6347 Yup this would work great.

**Comment by ff6347** [comment]
@all-contributors please add @thenbe for idea
